locations = [
    {"name": "Space ship", "image": "space_ship.jpeg"},
    {"name": "Hogwarts", "image": "hogwards.jpeg"},
    {"name": "Beach", "image": "beach.jpeg"},
    {"name": "University", "image": "university.jpeg"},
    {"name": "Supermarket", "image": "supermarket.jpeg"},
    {"name": "Airport", "image": "airport.jpeg"},
    {"name": "Disneyland", "image": "disneyland.jpeg"},
    {"name": "Dentist", "image": "dentist.jpeg"},
    {"name": "Chocolate factory", "image": "chovolate_factory.jpeg"},
    {"name": "FBI headquarters", "image": "fbi_headquarters.jpeg"},
    {"name": "Court", "image": "court.jpeg"},
    {"name": "Oval office", "image": "oval_office.jpeg"},
    {"name": "Ski resort", "image": "ski_resort.jpeg"},
    {"name": "Flower shop", "image": "flower_shop.jpeg"},
    {"name": "Prison", "image": "prison.jpeg"},
    {"name": "Cinema", "image": "cinema.jpeg"},
    {"name": "Tropical island", "image": "tropical_island.jpeg"},
    {"name": "Sushi restaurant", "image": "sushi_restaurant.jpeg"},
    {"name": "Underground bunker", "image": "underground_bunker.jpeg"},
    {"name": "Magic shop", "image": "magic_shop.jpeg"},
    {"name": "Pirate ship", "image": "pirate_ship.jpeg"},
    {"name": "Las Vegas casino", "image": "las_vegas_casino.jpeg"},
    {"name": "Subway during rush hour", "image": "subway_during_rush_hour.jpeg"},
    {"name": "Opera house", "image": "opera_house.jpeg"},
    {"name": "Zoo", "image": "zoo.jpeg"},
    {"name": "Medieval castle", "image": "medieval_castle.jpeg"},
    {"name": "Vampire lair", "image": "vampire_lair.jpeg"},
    {"name": "Rally race", "image": "rally_race.jpeg"},
    {"name": "Jungle expedition", "image": "jungle_expedition.jpeg"},
    {"name": "TV show set", "image": "tv_show_set.jpeg"},
    {"name": "Construction site", "image": "construction_site.jpeg"},
    {"name": "Hot air balloon", "image": "hot_air_balloon.jpeg"},
    {"name": "Water park", "image": "water_park.jpeg"},
    {"name": "Alien planet", "image": "alien_planet.jpeg"},
    {"name": "Music festival", "image": "music_festival.jpeg"},
    {"name": "Supervillain's secret lair", "image": "supervillains_ secret_lair.jpeg"},
    {"name": "Underground jazz club", "image": "underground_bunker.jpeg"},
]